name: CI for UrLSH

on:
  push:
    branches: [ "main", "dev" ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ "main", "dev" ]

# Donner la permission pour écrire dans les releases 
permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Set up la version de Java
    - name: Set JVM 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # 2. Donner les permission pour exécuter le script maven
    - name: Grant exuction permission for the mvnw
      run: chmod +x mvnw

    # 3. Lancer les tests et build
    - name: Run the unitests
      run: ./mvnw clean verify

    # 4. Sauvegarder le JAR pour la release
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: url-shortener
        path: target/url-shortener.jar
        retention-days: 1
    
    # 5. Création de la release
    - name: Create the release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/*.jar
        generate_release_notes: true